// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace pt {
class obj_user_game_record;
class obj_user_game_recordDefaultTypeInternal;
extern obj_user_game_recordDefaultTypeInternal _obj_user_game_record_default_instance_;
class obj_user_info;
class obj_user_infoDefaultTypeInternal;
extern obj_user_infoDefaultTypeInternal _obj_user_info_default_instance_;
class req_login;
class req_loginDefaultTypeInternal;
extern req_loginDefaultTypeInternal _req_login_default_instance_;
class rsp_login;
class rsp_loginDefaultTypeInternal;
extern rsp_loginDefaultTypeInternal _rsp_login_default_instance_;
}  // namespace pt
PROTOBUF_NAMESPACE_OPEN
template<> ::pt::obj_user_game_record* Arena::CreateMaybeMessage<::pt::obj_user_game_record>(Arena*);
template<> ::pt::obj_user_info* Arena::CreateMaybeMessage<::pt::obj_user_info>(Arena*);
template<> ::pt::req_login* Arena::CreateMaybeMessage<::pt::req_login>(Arena*);
template<> ::pt::rsp_login* Arena::CreateMaybeMessage<::pt::rsp_login>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pt {

enum rsp_login_RET : int {
  rsp_login_RET_SUCCESS = 0,
  rsp_login_RET_ACCOUNT_NULL = 1,
  rsp_login_RET_ACCOUNT_LOCK = 2,
  rsp_login_RET_PASSWORD_ERROR = 3,
  rsp_login_RET_ERROR = 10,
  rsp_login_RET_rsp_login_RET_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  rsp_login_RET_rsp_login_RET_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool rsp_login_RET_IsValid(int value);
constexpr rsp_login_RET rsp_login_RET_RET_MIN = rsp_login_RET_SUCCESS;
constexpr rsp_login_RET rsp_login_RET_RET_MAX = rsp_login_RET_ERROR;
constexpr int rsp_login_RET_RET_ARRAYSIZE = rsp_login_RET_RET_MAX + 1;

const std::string& rsp_login_RET_Name(rsp_login_RET value);
template<typename T>
inline const std::string& rsp_login_RET_Name(T enum_t_value) {
  static_assert(::std::is_same<T, rsp_login_RET>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function rsp_login_RET_Name.");
  return rsp_login_RET_Name(static_cast<rsp_login_RET>(enum_t_value));
}
bool rsp_login_RET_Parse(
    const std::string& name, rsp_login_RET* value);
// ===================================================================

class req_login :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pt.req_login) */ {
 public:
  req_login();
  virtual ~req_login();

  req_login(const req_login& from);
  req_login(req_login&& from) noexcept
    : req_login() {
    *this = ::std::move(from);
  }

  inline req_login& operator=(const req_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline req_login& operator=(req_login&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const req_login& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const req_login* internal_default_instance() {
    return reinterpret_cast<const req_login*>(
               &_req_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(req_login& a, req_login& b) {
    a.Swap(&b);
  }
  inline void Swap(req_login* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline req_login* New() const final {
    return CreateMaybeMessage<req_login>(nullptr);
  }

  req_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<req_login>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const req_login& from);
  void MergeFrom(const req_login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(req_login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.req_login";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  void set_username(const std::string& value);
  void set_username(std::string&& value);
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  std::string* mutable_username();
  std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:pt.req_login)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class obj_user_info :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pt.obj_user_info) */ {
 public:
  obj_user_info();
  virtual ~obj_user_info();

  obj_user_info(const obj_user_info& from);
  obj_user_info(obj_user_info&& from) noexcept
    : obj_user_info() {
    *this = ::std::move(from);
  }

  inline obj_user_info& operator=(const obj_user_info& from) {
    CopyFrom(from);
    return *this;
  }
  inline obj_user_info& operator=(obj_user_info&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const obj_user_info& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const obj_user_info* internal_default_instance() {
    return reinterpret_cast<const obj_user_info*>(
               &_obj_user_info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(obj_user_info& a, obj_user_info& b) {
    a.Swap(&b);
  }
  inline void Swap(obj_user_info* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline obj_user_info* New() const final {
    return CreateMaybeMessage<obj_user_info>(nullptr);
  }

  obj_user_info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<obj_user_info>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const obj_user_info& from);
  void MergeFrom(const obj_user_info& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(obj_user_info* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.obj_user_info";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kIconFieldNumber = 2,
    kLocationFieldNumber = 4,
    kCoinFieldNumber = 3,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  void set_nickname(const std::string& value);
  void set_nickname(std::string&& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  std::string* mutable_nickname();
  std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string icon = 2;
  void clear_icon();
  const std::string& icon() const;
  void set_icon(const std::string& value);
  void set_icon(std::string&& value);
  void set_icon(const char* value);
  void set_icon(const char* value, size_t size);
  std::string* mutable_icon();
  std::string* release_icon();
  void set_allocated_icon(std::string* icon);
  private:
  const std::string& _internal_icon() const;
  void _internal_set_icon(const std::string& value);
  std::string* _internal_mutable_icon();
  public:

  // string location = 4;
  void clear_location();
  const std::string& location() const;
  void set_location(const std::string& value);
  void set_location(std::string&& value);
  void set_location(const char* value);
  void set_location(const char* value, size_t size);
  std::string* mutable_location();
  std::string* release_location();
  void set_allocated_location(std::string* location);
  private:
  const std::string& _internal_location() const;
  void _internal_set_location(const std::string& value);
  std::string* _internal_mutable_location();
  public:

  // int64 coin = 3;
  void clear_coin();
  ::PROTOBUF_NAMESPACE_ID::int64 coin() const;
  void set_coin(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_coin() const;
  void _internal_set_coin(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:pt.obj_user_info)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr icon_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr location_;
  ::PROTOBUF_NAMESPACE_ID::int64 coin_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class obj_user_game_record :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pt.obj_user_game_record) */ {
 public:
  obj_user_game_record();
  virtual ~obj_user_game_record();

  obj_user_game_record(const obj_user_game_record& from);
  obj_user_game_record(obj_user_game_record&& from) noexcept
    : obj_user_game_record() {
    *this = ::std::move(from);
  }

  inline obj_user_game_record& operator=(const obj_user_game_record& from) {
    CopyFrom(from);
    return *this;
  }
  inline obj_user_game_record& operator=(obj_user_game_record&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const obj_user_game_record& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const obj_user_game_record* internal_default_instance() {
    return reinterpret_cast<const obj_user_game_record*>(
               &_obj_user_game_record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(obj_user_game_record& a, obj_user_game_record& b) {
    a.Swap(&b);
  }
  inline void Swap(obj_user_game_record* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline obj_user_game_record* New() const final {
    return CreateMaybeMessage<obj_user_game_record>(nullptr);
  }

  obj_user_game_record* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<obj_user_game_record>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const obj_user_game_record& from);
  void MergeFrom(const obj_user_game_record& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(obj_user_game_record* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.obj_user_game_record";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kKillFieldNumber = 2,
    kDeadFieldNumber = 3,
    kAssistFieldNumber = 4,
  };
  // string time = 1;
  void clear_time();
  const std::string& time() const;
  void set_time(const std::string& value);
  void set_time(std::string&& value);
  void set_time(const char* value);
  void set_time(const char* value, size_t size);
  std::string* mutable_time();
  std::string* release_time();
  void set_allocated_time(std::string* time);
  private:
  const std::string& _internal_time() const;
  void _internal_set_time(const std::string& value);
  std::string* _internal_mutable_time();
  public:

  // int32 kill = 2;
  void clear_kill();
  ::PROTOBUF_NAMESPACE_ID::int32 kill() const;
  void set_kill(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_kill() const;
  void _internal_set_kill(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 dead = 3;
  void clear_dead();
  ::PROTOBUF_NAMESPACE_ID::int32 dead() const;
  void set_dead(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_dead() const;
  void _internal_set_dead(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 assist = 4;
  void clear_assist();
  ::PROTOBUF_NAMESPACE_ID::int32 assist() const;
  void set_assist(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_assist() const;
  void _internal_set_assist(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:pt.obj_user_game_record)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
  ::PROTOBUF_NAMESPACE_ID::int32 kill_;
  ::PROTOBUF_NAMESPACE_ID::int32 dead_;
  ::PROTOBUF_NAMESPACE_ID::int32 assist_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class rsp_login :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:pt.rsp_login) */ {
 public:
  rsp_login();
  virtual ~rsp_login();

  rsp_login(const rsp_login& from);
  rsp_login(rsp_login&& from) noexcept
    : rsp_login() {
    *this = ::std::move(from);
  }

  inline rsp_login& operator=(const rsp_login& from) {
    CopyFrom(from);
    return *this;
  }
  inline rsp_login& operator=(rsp_login&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const rsp_login& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const rsp_login* internal_default_instance() {
    return reinterpret_cast<const rsp_login*>(
               &_rsp_login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(rsp_login& a, rsp_login& b) {
    a.Swap(&b);
  }
  inline void Swap(rsp_login* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline rsp_login* New() const final {
    return CreateMaybeMessage<rsp_login>(nullptr);
  }

  rsp_login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<rsp_login>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const rsp_login& from);
  void MergeFrom(const rsp_login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(rsp_login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pt.rsp_login";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef rsp_login_RET RET;
  static constexpr RET SUCCESS =
    rsp_login_RET_SUCCESS;
  static constexpr RET ACCOUNT_NULL =
    rsp_login_RET_ACCOUNT_NULL;
  static constexpr RET ACCOUNT_LOCK =
    rsp_login_RET_ACCOUNT_LOCK;
  static constexpr RET PASSWORD_ERROR =
    rsp_login_RET_PASSWORD_ERROR;
  static constexpr RET ERROR =
    rsp_login_RET_ERROR;
  static inline bool RET_IsValid(int value) {
    return rsp_login_RET_IsValid(value);
  }
  static constexpr RET RET_MIN =
    rsp_login_RET_RET_MIN;
  static constexpr RET RET_MAX =
    rsp_login_RET_RET_MAX;
  static constexpr int RET_ARRAYSIZE =
    rsp_login_RET_RET_ARRAYSIZE;
  template<typename T>
  static inline const std::string& RET_Name(T enum_t_value) {
    static_assert(::std::is_same<T, RET>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function RET_Name.");
    return rsp_login_RET_Name(enum_t_value);
  }
  static inline bool RET_Parse(const std::string& name,
      RET* value) {
    return rsp_login_RET_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kRecordFieldNumber = 3,
    kUserInfoFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // repeated .pt.obj_user_game_record record = 3;
  int record_size() const;
  private:
  int _internal_record_size() const;
  public:
  void clear_record();
  ::pt::obj_user_game_record* mutable_record(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >*
      mutable_record();
  private:
  const ::pt::obj_user_game_record& _internal_record(int index) const;
  ::pt::obj_user_game_record* _internal_add_record();
  public:
  const ::pt::obj_user_game_record& record(int index) const;
  ::pt::obj_user_game_record* add_record();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >&
      record() const;

  // .pt.obj_user_info user_info = 2;
  bool has_user_info() const;
  private:
  bool _internal_has_user_info() const;
  public:
  void clear_user_info();
  const ::pt::obj_user_info& user_info() const;
  ::pt::obj_user_info* release_user_info();
  ::pt::obj_user_info* mutable_user_info();
  void set_allocated_user_info(::pt::obj_user_info* user_info);
  private:
  const ::pt::obj_user_info& _internal_user_info() const;
  ::pt::obj_user_info* _internal_mutable_user_info();
  public:

  // int32 ret = 1;
  void clear_ret();
  ::PROTOBUF_NAMESPACE_ID::int32 ret() const;
  void set_ret(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ret() const;
  void _internal_set_ret(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:pt.rsp_login)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record > record_;
  ::pt::obj_user_info* user_info_;
  ::PROTOBUF_NAMESPACE_ID::int32 ret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// req_login

// string username = 1;
inline void req_login::clear_username() {
  username_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& req_login::username() const {
  // @@protoc_insertion_point(field_get:pt.req_login.username)
  return _internal_username();
}
inline void req_login::set_username(const std::string& value) {
  _internal_set_username(value);
  // @@protoc_insertion_point(field_set:pt.req_login.username)
}
inline std::string* req_login::mutable_username() {
  // @@protoc_insertion_point(field_mutable:pt.req_login.username)
  return _internal_mutable_username();
}
inline const std::string& req_login::_internal_username() const {
  return username_.GetNoArena();
}
inline void req_login::_internal_set_username(const std::string& value) {
  
  username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void req_login::set_username(std::string&& value) {
  
  username_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.req_login.username)
}
inline void req_login::set_username(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.req_login.username)
}
inline void req_login::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.req_login.username)
}
inline std::string* req_login::_internal_mutable_username() {
  
  return username_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* req_login::release_username() {
  // @@protoc_insertion_point(field_release:pt.req_login.username)
  
  return username_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.username)
}

// string password = 2;
inline void req_login::clear_password() {
  password_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& req_login::password() const {
  // @@protoc_insertion_point(field_get:pt.req_login.password)
  return _internal_password();
}
inline void req_login::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:pt.req_login.password)
}
inline std::string* req_login::mutable_password() {
  // @@protoc_insertion_point(field_mutable:pt.req_login.password)
  return _internal_mutable_password();
}
inline const std::string& req_login::_internal_password() const {
  return password_.GetNoArena();
}
inline void req_login::_internal_set_password(const std::string& value) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void req_login::set_password(std::string&& value) {
  
  password_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.req_login.password)
}
inline void req_login::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.req_login.password)
}
inline void req_login::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.req_login.password)
}
inline std::string* req_login::_internal_mutable_password() {
  
  return password_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* req_login::release_password() {
  // @@protoc_insertion_point(field_release:pt.req_login.password)
  
  return password_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void req_login::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pt.req_login.password)
}

// -------------------------------------------------------------------

// obj_user_info

// string nickname = 1;
inline void obj_user_info::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& obj_user_info::nickname() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.nickname)
  return _internal_nickname();
}
inline void obj_user_info::set_nickname(const std::string& value) {
  _internal_set_nickname(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.nickname)
}
inline std::string* obj_user_info::mutable_nickname() {
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.nickname)
  return _internal_mutable_nickname();
}
inline const std::string& obj_user_info::_internal_nickname() const {
  return nickname_.GetNoArena();
}
inline void obj_user_info::_internal_set_nickname(const std::string& value) {
  
  nickname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void obj_user_info::set_nickname(std::string&& value) {
  
  nickname_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.obj_user_info.nickname)
}
inline void obj_user_info::set_nickname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nickname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.nickname)
}
inline void obj_user_info::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.nickname)
}
inline std::string* obj_user_info::_internal_mutable_nickname() {
  
  return nickname_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* obj_user_info::release_nickname() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.nickname)
  
  return nickname_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.nickname)
}

// string icon = 2;
inline void obj_user_info::clear_icon() {
  icon_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& obj_user_info::icon() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.icon)
  return _internal_icon();
}
inline void obj_user_info::set_icon(const std::string& value) {
  _internal_set_icon(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.icon)
}
inline std::string* obj_user_info::mutable_icon() {
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.icon)
  return _internal_mutable_icon();
}
inline const std::string& obj_user_info::_internal_icon() const {
  return icon_.GetNoArena();
}
inline void obj_user_info::_internal_set_icon(const std::string& value) {
  
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void obj_user_info::set_icon(std::string&& value) {
  
  icon_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.obj_user_info.icon)
}
inline void obj_user_info::set_icon(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.icon)
}
inline void obj_user_info::set_icon(const char* value, size_t size) {
  
  icon_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.icon)
}
inline std::string* obj_user_info::_internal_mutable_icon() {
  
  return icon_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* obj_user_info::release_icon() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.icon)
  
  return icon_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_icon(std::string* icon) {
  if (icon != nullptr) {
    
  } else {
    
  }
  icon_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), icon);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.icon)
}

// int64 coin = 3;
inline void obj_user_info::clear_coin() {
  coin_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 obj_user_info::_internal_coin() const {
  return coin_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 obj_user_info::coin() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.coin)
  return _internal_coin();
}
inline void obj_user_info::_internal_set_coin(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  coin_ = value;
}
inline void obj_user_info::set_coin(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_coin(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.coin)
}

// string location = 4;
inline void obj_user_info::clear_location() {
  location_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& obj_user_info::location() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_info.location)
  return _internal_location();
}
inline void obj_user_info::set_location(const std::string& value) {
  _internal_set_location(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_info.location)
}
inline std::string* obj_user_info::mutable_location() {
  // @@protoc_insertion_point(field_mutable:pt.obj_user_info.location)
  return _internal_mutable_location();
}
inline const std::string& obj_user_info::_internal_location() const {
  return location_.GetNoArena();
}
inline void obj_user_info::_internal_set_location(const std::string& value) {
  
  location_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void obj_user_info::set_location(std::string&& value) {
  
  location_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.obj_user_info.location)
}
inline void obj_user_info::set_location(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  location_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_info.location)
}
inline void obj_user_info::set_location(const char* value, size_t size) {
  
  location_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_info.location)
}
inline std::string* obj_user_info::_internal_mutable_location() {
  
  return location_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* obj_user_info::release_location() {
  // @@protoc_insertion_point(field_release:pt.obj_user_info.location)
  
  return location_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_info::set_allocated_location(std::string* location) {
  if (location != nullptr) {
    
  } else {
    
  }
  location_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), location);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_info.location)
}

// -------------------------------------------------------------------

// obj_user_game_record

// string time = 1;
inline void obj_user_game_record::clear_time() {
  time_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& obj_user_game_record::time() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.time)
  return _internal_time();
}
inline void obj_user_game_record::set_time(const std::string& value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.time)
}
inline std::string* obj_user_game_record::mutable_time() {
  // @@protoc_insertion_point(field_mutable:pt.obj_user_game_record.time)
  return _internal_mutable_time();
}
inline const std::string& obj_user_game_record::_internal_time() const {
  return time_.GetNoArena();
}
inline void obj_user_game_record::_internal_set_time(const std::string& value) {
  
  time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void obj_user_game_record::set_time(std::string&& value) {
  
  time_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pt.obj_user_game_record.time)
}
inline void obj_user_game_record::set_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt.obj_user_game_record.time)
}
inline void obj_user_game_record::set_time(const char* value, size_t size) {
  
  time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt.obj_user_game_record.time)
}
inline std::string* obj_user_game_record::_internal_mutable_time() {
  
  return time_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* obj_user_game_record::release_time() {
  // @@protoc_insertion_point(field_release:pt.obj_user_game_record.time)
  
  return time_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void obj_user_game_record::set_allocated_time(std::string* time) {
  if (time != nullptr) {
    
  } else {
    
  }
  time_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), time);
  // @@protoc_insertion_point(field_set_allocated:pt.obj_user_game_record.time)
}

// int32 kill = 2;
inline void obj_user_game_record::clear_kill() {
  kill_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::_internal_kill() const {
  return kill_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::kill() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.kill)
  return _internal_kill();
}
inline void obj_user_game_record::_internal_set_kill(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  kill_ = value;
}
inline void obj_user_game_record::set_kill(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_kill(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.kill)
}

// int32 dead = 3;
inline void obj_user_game_record::clear_dead() {
  dead_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::_internal_dead() const {
  return dead_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::dead() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.dead)
  return _internal_dead();
}
inline void obj_user_game_record::_internal_set_dead(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  dead_ = value;
}
inline void obj_user_game_record::set_dead(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_dead(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.dead)
}

// int32 assist = 4;
inline void obj_user_game_record::clear_assist() {
  assist_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::_internal_assist() const {
  return assist_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 obj_user_game_record::assist() const {
  // @@protoc_insertion_point(field_get:pt.obj_user_game_record.assist)
  return _internal_assist();
}
inline void obj_user_game_record::_internal_set_assist(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  assist_ = value;
}
inline void obj_user_game_record::set_assist(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_assist(value);
  // @@protoc_insertion_point(field_set:pt.obj_user_game_record.assist)
}

// -------------------------------------------------------------------

// rsp_login

// int32 ret = 1;
inline void rsp_login::clear_ret() {
  ret_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rsp_login::_internal_ret() const {
  return ret_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 rsp_login::ret() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.ret)
  return _internal_ret();
}
inline void rsp_login::_internal_set_ret(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  ret_ = value;
}
inline void rsp_login::set_ret(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:pt.rsp_login.ret)
}

// .pt.obj_user_info user_info = 2;
inline bool rsp_login::_internal_has_user_info() const {
  return this != internal_default_instance() && user_info_ != nullptr;
}
inline bool rsp_login::has_user_info() const {
  return _internal_has_user_info();
}
inline void rsp_login::clear_user_info() {
  if (GetArenaNoVirtual() == nullptr && user_info_ != nullptr) {
    delete user_info_;
  }
  user_info_ = nullptr;
}
inline const ::pt::obj_user_info& rsp_login::_internal_user_info() const {
  const ::pt::obj_user_info* p = user_info_;
  return p != nullptr ? *p : *reinterpret_cast<const ::pt::obj_user_info*>(
      &::pt::_obj_user_info_default_instance_);
}
inline const ::pt::obj_user_info& rsp_login::user_info() const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.user_info)
  return _internal_user_info();
}
inline ::pt::obj_user_info* rsp_login::release_user_info() {
  // @@protoc_insertion_point(field_release:pt.rsp_login.user_info)
  
  ::pt::obj_user_info* temp = user_info_;
  user_info_ = nullptr;
  return temp;
}
inline ::pt::obj_user_info* rsp_login::_internal_mutable_user_info() {
  
  if (user_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::pt::obj_user_info>(GetArenaNoVirtual());
    user_info_ = p;
  }
  return user_info_;
}
inline ::pt::obj_user_info* rsp_login::mutable_user_info() {
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.user_info)
  return _internal_mutable_user_info();
}
inline void rsp_login::set_allocated_user_info(::pt::obj_user_info* user_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete user_info_;
  }
  if (user_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      user_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_info, submessage_arena);
    }
    
  } else {
    
  }
  user_info_ = user_info;
  // @@protoc_insertion_point(field_set_allocated:pt.rsp_login.user_info)
}

// repeated .pt.obj_user_game_record record = 3;
inline int rsp_login::_internal_record_size() const {
  return record_.size();
}
inline int rsp_login::record_size() const {
  return _internal_record_size();
}
inline void rsp_login::clear_record() {
  record_.Clear();
}
inline ::pt::obj_user_game_record* rsp_login::mutable_record(int index) {
  // @@protoc_insertion_point(field_mutable:pt.rsp_login.record)
  return record_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >*
rsp_login::mutable_record() {
  // @@protoc_insertion_point(field_mutable_list:pt.rsp_login.record)
  return &record_;
}
inline const ::pt::obj_user_game_record& rsp_login::_internal_record(int index) const {
  return record_.Get(index);
}
inline const ::pt::obj_user_game_record& rsp_login::record(int index) const {
  // @@protoc_insertion_point(field_get:pt.rsp_login.record)
  return _internal_record(index);
}
inline ::pt::obj_user_game_record* rsp_login::_internal_add_record() {
  return record_.Add();
}
inline ::pt::obj_user_game_record* rsp_login::add_record() {
  // @@protoc_insertion_point(field_add:pt.rsp_login.record)
  return _internal_add_record();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::pt::obj_user_game_record >&
rsp_login::record() const {
  // @@protoc_insertion_point(field_list:pt.rsp_login.record)
  return record_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pt

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::pt::rsp_login_RET> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
